config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  post 'posts/create' => 'posts#create'
  root 'topics#index'
  get '/topics/:id' => 'topics#show', as: :topics_show
  post 'topics/create' => 'topics#create'
  delete 'topics/delete/:id' => 'topics#delete', as: :topic_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :post, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def create
    @posts = Post.new(params[:post].permit(:topic_id, :name, :body))
    @posts.save
    redirect_to "/topics/:id"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @newTopic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic].permit(:title))
    @topic.save
    redirect_to root_path
  end

  def delete
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to root_path
  end

  def show
    @topic = Topic.find(params[:id])
    @newpost = Post.new(:topic_id => params[:id])
    @posts = Post.where(topic_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag 'post.ico' %>
    <title>PreTrainingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/topics/index.html.erb
<h1>トピック一覧</h1>
<ul>
  <% @topics.each do |topic| %>
  <li>
  <%= link_to topic.title, topics_show_path(topic.id) %>
  <%= link_to '[削除]', topic_delete_path(topic.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: '本当に削除してよろしいでしょうか？？'  }%>
  </li>
  <% end %>
</ul>
<h1>トピック新規登録</h1>
<%= form_for @newTopic, :url => {:action => 'create'} do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>

<% @posts.each_with_index do |post , idx| %>
  <p>
    <%= idx + 1 %>. <%= post.name %> : <%= post.body %>
  </p>
<% end %>

<h3>新規書き込み</h3>
<%= form_for @newpost, :url => posts_create_path do |f| %>
  <p>お名前</p>
  <p><%= f.text_field :name %></p>
  <p>本文</p>
  <p><%= f.text_area :body %></p>
  
  <%= f.hidden_field :topic_id %>
  <%= f.submit %>
<% end %>

<%= link_to root_path do %>
<button>戻る</button>
<% end %>